### ISSUE TITLE
Infinite loading screen on BitRemote launch when qbitorrent does not have any tasks

### ISSUE THREAD

**Issue by 3zero2** [tatsuz0u/BitRemote#44] opened 2024-07-12 17:51 UTC
My qbitorrent instance is behind a reverse proxy. When I try to connect I get the error below. 

Any idea on how to resolve this?

Thank you. 

![image](https://github.com/user-attachments/assets/8fe1f609-e736-40f1-9595-ff91eff6cabe)

**Comment by tatsuzo-arkstudios** [comment] 2024-08-15 06:38
Sorry for the late reply.
Did you setup a http basic authentication for the reverse proxy?

**Comment by 3zero2** [comment] 2024-08-16 14:23
What I have discovered in the meantime is that opening Bitremote when my Qbitorrent server has no active torrents results in a permanent loading screen:

<img width="999" alt="Screenshot 2024-08-16 at 16 21 10" src="https://github.com/user-attachments/assets/0f981c64-c5dd-4e49-af8b-8a20be986d5b">

If there is an active torrent then Bitremote manages to load the data correctly. I can even delete the torrent and get to this screen:

<img width="1002" alt="Screenshot 2024-08-16 at 16 20 57" src="https://github.com/user-attachments/assets/1d75be56-f485-44a0-9690-bd2692836d44">

But as said above, this screen doesn't manage to load when there are no active torrent when app is launched.

**Comment by tatsuz0u** [comment] 2024-08-16 14:32
Thank you for your detailed feedback.
It appears that the authentication issue has been resolved.

However, the loading page could be due to a data conversion issue.
Could you please also let us know which version of qBittorrent you are using?

**Comment by 3zero2** [comment] 2024-08-16 15:31
I'm using qBittorrent Version 4.6.5

**Comment by 3zero2** [comment] 2024-09-08 20:49
Just updated to BitRemote 1.2.0 and the issue persists.

**Comment by tatsuz0u** [comment] 2024-09-08 23:45
Thanks for the update for this issue. We haven’t yet investigated this issue but will be looking into it. We appreciate your patience as we work on this. 🙏

**Comment by tatsuzo-arkstudios** [comment] 2024-09-18 13:58
@3zero2 
I have been using my qBittorrent behind a reverse proxy too and I have updated it to 4.6.5. Unfortunately I could not reproduce the issue in my environment.

Could you tell me how you authenticate with your instance? For example, what happens when you access your instance's WebUI in the browser?

- Http basic auth
  - A dialog pops up and asks for your username & pass
<img width="500" alt="image" src="https://github.com/user-attachments/assets/1087d21a-fd9c-4e43-a61b-4f8636fc6a9e">

(PS: This is not actually a screenshot of a http basic auth dialog for a qBittorrent instance. But they should look the same.)

- WebUI login auth
  - The qBittorrent WebUI login page shows up and asks for your username & pass
<img width="500" alt="image" src="https://github.com/user-attachments/assets/7f3e2419-a79c-4bb5-b2a4-71ab3a76710b">


Http basic auth or WebUI login auth, or both? 🤔

**Comment by 3zero2** [comment] 2024-09-18 14:20
Thank you for trying to reproduce the issue @tatsuzo-arkstudios.

I'm using the WebUI login:

<img width="332" alt="Screenshot 2024-09-18 at 16 06 48" src="https://github.com/user-attachments/assets/e266cadc-6d18-4cb6-aac9-369344634426">

In my case it looks a bit different as I'm using the [VueTorrent](https://github.com/VueTorrent/VueTorrent) WebUI.

**Comment by tatsuzo-arkstudios** [comment] 2024-09-18 14:26
@3zero2 Thank you for the extra information.

Could you please try accessing your instance using the original WebUI? If the original one is available, then please try using the link to the original WebUI as BitRemote client host. 🤔

**Comment by 3zero2** [comment] 2024-09-19 12:59
@tatsuzo-arkstudios 

Still happens with the default WebUI. Are there any logs I can provide?

**Comment by tatsuzo-arkstudios** [comment] 2024-10-27 08:07
Finally reproduced. We’ll look into this and aim to resolve it in the next update.

**Comment by tatsuzo-arkstudios** [comment] 2024-11-04 08:24
@3zero2 This issue should have been fixed in BitRemote 1.3.0. 😋

**Closed as completed** 2024-11-05 14:36 UTC
